spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:mem:locationtraker"
    driverClassName: "org.h2.Driver"
    username: sa
    password: password
server:
  port: 9001

